routingPanier:
    resource: "@EcommerceBundle/Resources/config/Routings/routingPanier.yml"
    prefix:   /panier

routingProduit:
    resource: "@EcommerceBundle/Resources/config/Routings/routingProduit.yml"
    prefix:   /

ecommerce_adminProduits:
    resource: "@EcommerceBundle/Resources/config/routing/produits.yml"
    prefix:   /admin/produits

ecommerce_adminCategories:
    resource: "@EcommerceBundle/Resources/config/routing/categories.yml"
    prefix:   /admin/categories
