routingPanier:
    resource: "@EcommerceBundle/Resources/config/Routings/routingPanier.yml"
    prefix:   /panier

routingProduit:
    resource: "@EcommerceBundle/Resources/config/Routings/routingProduit.yml"
    prefix:   /