services:

    setNewReference:
      class: Ecommerce\EcommerceBundle\Services\GetReference
      arguments: ['@security.context','@doctrine.orm.entity_manager']

    tva:
      class: Ecommerce\EcommerceBundle\Twig\Extension\TvaExtension
      tags:
        - { name: twig.extension}

    redirectonListener:
      class: Ecommerce\EcommerceBundle\Listener\RedirectionListener
      arguments: ['@service_container','@session']
      tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    languageListener:
      class: Ecommerce\EcommerceBundle\Listener\LanguageListener
      arguments: ['@session','%kernel.default_locale%']
      tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
