<?php

namespace Users\UsersBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesRepository extends EntityRepository
{
    
    public function byFacture($user)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.user = :u')
            ->andWhere('c.valider = 1')
            ->andWhere('c.reference != 0')
            ->orderBy('c.date','DESC')
            ->setParameter('u',$user );

        return $qb->getQuery()->getResult();
    }

    public function ByDateCommande($date)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.date >= :d')
            ->andWhere('c.valider = 1')
            ->andWhere('c.reference != 0')
            ->orderBy('c.date')
            ->setParameter('d',$date );

        return $qb->getQuery()->getResult();
    }
    
}
