<?php

namespace Users\UsersBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * UsersAdressesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersAdressesRepository extends EntityRepository
{
}
