<?php

namespace Users\UsersBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * VillesMarocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VillesMarocRepository extends EntityRepository
{
    public function byNom($nom)
    {
        $qb = $this->createQueryBuilder('v')
            ->select('v')
            ->where('v.ville LIKE :n')
            ->setParameter('n',$nom.'%' )
            ->orderBy('v.ville')
            ;
        return $qb->getQuery()->getResult();
    }
}
