users_adminCommandes:
    resource: "@UsersBundle/Resources/config/routing/commandes.yml"
    prefix:   /admin/commandes

adresses:
    path:     /profile/adresses
    defaults: { _controller: UsersBundle:User:adresses }

facture:
    path:     /profile/factures
    defaults: { _controller: UsersBundle:User:facture }

validationCommande:
    path:     /panier/validation/validationCommande/{id}
    defaults: { _controller: UsersBundle:Commandes:validationCommande }

pdf:
    path:     /downloadFacture/{commande}
    defaults: { _controller: UsersBundle:User:facturePDF }