users_adminCommandes:
    resource: "@UsersBundle/Resources/config/routing/commandes.yml"
    prefix:   /admin/commandes

users_adminUsers:
    resource: "@UsersBundle/Resources/config/routing/user.yml"
    prefix:   /admin/users

users_admin:
    path:     /admin
    defaults: { _controller: "UsersBundle:UserAdmin:admin" }
    methods:  GET

adresses:
    path:     /profile/adresses
    defaults: { _controller: UsersBundle:User:adresses }

facture:
    path:     /profile/factures
    defaults: { _controller: UsersBundle:User:facture }

validationCommande:
    path:     /panier/validation/validationCommande/{id}
    defaults: { _controller: UsersBundle:Commandes:validationCommande }

pdf:
    path:     /downloadFacture/{commande}
    defaults: { _controller: UsersBundle:User:facturePDF }

ville:
    path:     /ville/{nom}
    defaults: { _controller: UsersBundle:User:ville }
    options:
            expose: true