produits:
    path:     /
    defaults: { _controller: EcommerceBundle:Produits:produits }

presentation:
    path:     /produit/{id}
    defaults: { _controller: EcommerceBundle:Produits:presentation }

produitsCategorie:
    path:     /ProduitsCategorie/{categorie}
    defaults: { _controller: EcommerceBundle:Produits:produits }

all_categories:
    path:     /all
    defaults: { _controller: EcommerceBundle:Categories:allCategories }

search:
    path:     /search
    defaults: { _controller: EcommerceBundle:Produits:search }
