<?php

namespace Ecommerce\EcommerceBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Ecommerce\EcommerceBundle\Entity\Produits;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends EntityRepository
{
    public function findByCategorie($id)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.categorie = :categorie')
            ->orderBy('p.id')
            ->setParameter('categorie',$id );

        return $qb->getQuery()->getResult();
    }
}
