<?php

namespace Ecommerce\EcommerceBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Ecommerce\EcommerceBundle\Entity\Produits;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends EntityRepository
{
    public function findByCategorie($id)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.categorie = :categorie')
            ->andWhere('p.disponible = :t')
            ->orderBy('p.id')
            ->setParameter('t',true )
            ->setParameter('categorie',$id );

        return $qb->getQuery()->getResult();
    }
    
    public function search($string)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.nom LIKE :s')
            ->andWhere('p.disponible = :t')
            ->orderBy('p.id')
            ->setParameter('t',true )
            ->setParameter('s','%'.$string.'%' );

        return $qb->getQuery()->getResult();
    }
}
